export const GET_CONVERSATION_REQUEST = "GET_CONVERSATION_REQUEST"
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS"
export const GET_CONVERSATION_FAILURE = "GET_CONVERSATION_FAILURE"
export const SET_CONVERSATION = "SET_CONVERSATION"
export const ADD_MESSAGE_REQUEST = "ADD_MESSAGE_REQUEST"
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS"
export const ADD_MESSAGE_FAILURE = "ADD_MESSAGE_FAILURE"

